spring:
  profiles:
    active: dev
  jpa:
    show-sql: true
#配置资源位置
  resources:
    static-locations: classpath:/static/ #静态资源加载位置
  freemarker:
      request-context-attribute: request #指定RequestContext属性的名.
      allow-request-override: false #指定HttpServletRequest的属性是否可以覆盖controller的model的同名项
      allow-session-override: false #指定HttpSession的属性是否可以覆盖controller的model的同名项
      cache: false  #关闭缓存
      charset: utf-8  #编码
      check-template-location: true #是否检查templates路径是否存在.
      content-type: text/html
      enabled: true #是否允许mvc使用freemarker.
      expose-request-attributes: false #设定所有request的属性在merge到模板的时候，是否要都添加到model中.
      expose-session-attributes: false #设定所有HttpSession的属性在merge到模板的时候，是否要都添加到model中.
      expose-spring-macro-helpers: true #设定是否以springMacroRequestContext的形式暴露RequestContext给Spring’s macro library使用
      prefer-file-system-access: true #是否优先从文件系统加载template，以支持热加载，默认为true
      suffix: .ftl #后缀
      template-loader-path: classpath:/templates/ #模板加载位置