server:
  port: 11111
  context-path: /dev
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.entertainment.erp.domain.vo
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/erp
    username: zhangzhi
    password: 123456