server:
  port: 11112
  context-path: /dev
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.sso.domain
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sso
    username: zhangzhi
    password: 123456